version: '2.1'

services:
  mysql:
    image: mysql:5
    container_name: ff-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ff
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/3306'" ]
      interval: 10s
      timeout: 10s
      retries: 6
